### ISSUE TITLE
文件"计划design.mm"，用freemind_1.0beta8打开失败

### ISSUE THREAD

**Issue by deathcult** [ichuan/jihua#3]
freemind 错误提示信息：
“Error while parsing file:freemind.main.XMLParseException: XML Parse Exception during parsing of the XML definition at line 1: Unexpected end of data reached”

**Comment by ichuan** [comment]
可能是 freemind 版本问题。我试了最新版 1.0.0 RC5 和最新稳定版 0.9.0，都可以正常打开此文件。

**Comment by deathcult** [comment]
是的，Freemind 0.9.0 stable可以正常打开。
谢谢！
